### ISSUE TITLE
Cray

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#118]
Some issues I managed to fix:
1. Need to add -fPIC flag in `append_property(SOURCE ${SRC_FTI_F90} 	PROPERTY COMPILE_FLAGS "${MPI_Fortran_COMPILE_FLAGS}")` and `append_property(SOURCE ${SRC_FTI}
    PROPERTY COMPILE_FLAGS "${MPI_C_COMPILE_FLAGS}" "${SIONLIB_CFLAGS}")`.
2. Need to add condition for finding openssl library:
`if(NOT DEFINED NO_OPENSSL)
	find_package(OPENSSL REQUIRED)
endif()
`

When compiling with openssl md5 I get error:
` cannot find -lssl` and `cannot find -lcrypto`

When compiling with built-in md5 algorithm I get new problem with fortran:
`undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'`

After changes 1 and 2, using built-in md5 and turning off fortran interface I don't have any problem with compiling fti on Cray system (I had to add 2 flags to cmake execution: `-D CMAKE_C_COMPILER="cc" -D CMAKE_Fortran_COMPILER="ftn"`

**Comment by kellekai** [comment]
On daint (Cray) I have no problem installing FTI, for both cases: intel and gcc (after adding -fPIC compiler flag because intel wants it and for gnu it doesn't harm). I not even have to set the compiler environment variables FC and CC, neither for intel nor gnu.

For **gnu** Environment: 
`module purge`
`module load gcc/5.3.0 CMake/3.6.2 craype/2.5.8 cray-mpich/7.5.0 PrgEnv-gnu/6.0.3`
`export CRAY_CPU_TARGET=x86-64`
`export CRAYPE_LINK_TYPE=dynamic`

for **intel** Environnment:
`module purge`
`module load intel/17.0.1.132 CMake/3.6.2 craype/2.5.8 cray-mpich/7.5.0 PrgEnv-intel/6.0.3`
`export CRAY_CPU_TARGET=x86-64`
`export CRAYPE_LINK_TYPE=dynamic`

However, I encounter problems when using `CMake/3.8.1`. In that case, the MPI environment is not set through cmake properly. It is important to load the programming environment modules: `PrgEnv-gnu` or `PrgEnv-intel` though.

I have found a cmake flag which might help in some cases for cray. To define in cmake command as: `CMAKE_SYSTEM_NAME=CrayLinuxEnvironment`

**Comment by ksiero** [comment]
I tried gnu and intel environment, but when I use newer version of Cmake I get:
`-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_SSL_LIBRARY OPENSSL_CRYPTO_LIBRARY) (found version "1.0.1i")
`
