### ISSUE TITLE
Use of the Cmake ExternalProject module

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#23]
The ExternalProject module can be used to build fti library dependencies (e.g. jerasure). 

The module makes it possible to download the external software components from the internet, run its configure step, build it and install it with just a few lines of code added to the CMakeLists.txt file.

**Comment by leobago** [comment]
That is an interesting idea. However, I think I prefer to keep all the necessary code of FTI in one single tar so that users don't need to care about dependencies. We only have a few dependencies so maybe this would be an overkill. Also, many supercomputers have very restrictive rules about accessing internet from the nodes, so the automatic download would not work in those cases. If you have other strong arguments for this idea I would be happy to hear them, otherwise we can close this issue.

**Comment by sclaomir** [comment]
Yes, you're absolutely right. This approach will be useless, if computing nodes have no internet access. It is a knock-out argument :)
