### ISSUE TITLE
Example application crashes during recovery

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#43]
If example application was running and was interrupted, in the config file `failure` is set to `1` and `exec_id` to the execution id. But if no checkpoints were taken during the first run, the application will crash during recovery.
`[ FTI  Information ] : Reading FTI configuration file (config.fti)...`
`[ FTI  Information ] : This is a restart. The execution ID is: 2016-06-07_12-42-13` 
`[ FTI  Information ] : No possible to restart from level 1.`
`[ FTI  Information ] : No possible to restart from level 2.`
`[ FTI  Information ] : No possible to restart from level 3.`
`[ FTI  Information ] : No possible to restart from level 4.`
`[ FTI  Information ] : FTI has been initialized.`
`[FTI Warning 000000] : FTI failed to recover the checkpoint files.`
`[FTI Warning 000000] : Error => Operation timed out`
...
`[FTI Warning 000013] : FTI failed to recover the checkpointed data.`
`[FTI Warning 000013] : Error => Is a directory`
`[FTI Error - 000013] : Could not read FTI checkpoint file. : Is a directory`
`[FTI Error - 000013] : Impossible to load the checkpoint data. : Is a directory`
`--------------------------------------------------------------------------`
`MPI_ABORT was invoked on rank 13 in communicator MPI_COMM_WORLD` 
`with errorcode -1.`

`NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.`
`You may or may not see output from other processes, depending on`
`exactly when Open MPI kills them.`
`--------------------------------------------------------------------------`

**Comment by leobago** [comment]
Yes,right. One solution could be to update the config file only after the first checkpoint.. or even better update it twice, once at FTI_Init and another one after the first checkpoint. What do you think?

**Comment by jbigot** [comment]
@leobago both option still make the app crash if the checkpoint is not correctly written at restart, am I wrong?
Wouldn't handling the situation at restart be much better?

**Comment by leobago** [comment]
So, the thing is that if the configuration file is only updated after the first checkpoint, if a failure happens, then, at restart FTI will believe this is a fresh start and not a recovery. The bottom-line is, if not checkpoint has been taken, then there is absolutely not way for recovery.

**Comment by jbigot** [comment]
A restart from before the first checkpoint is indeed equivalent to a fresh start. 
My point was that by requiring the config file to identify the run as such, you are introducing a potential bug if the checkpoint is not correctly written while the config file is updated (they are potentially on distinct FS). The solution where the restart code handles the case where the config file says restart but there is no checkpoint as a plain fresh start seems more robust.

**Comment by leobago** [comment]
Well, if the config file is updated *after* the checkpoint is known to be correctly written then the only way for the restart to fail is if the checkpoit data gets corrupted in the storage. Now, given that a failure could occur just after the checkpoint is finished but before the config file is updated, then the problematic scenario would be that FTI believe this is a fresh restart but in fact there is a checkpoint saved somewhere. Nonetheless, I agree with you that it is more robust to check at restart.
But then here is a question: right now the application "crashes" if it does not find a suitable checkpoint, but in fact the crash is during FTI_Init, so just at the initialization, is not like the application has been running for hours. Then, the user understand there is no checkpoint, can update the config file and relaunch a fresh execution. I did it this way because I thought it was better to clearly notify the user and let him launch a fresh execution. Do you think is better to simply print a message and then assume a fresh restart? What if the user passed the wrong configuration file linked to a previous failed execution, cannot restart and FTI assumes a fresh restart (burning CPU hours for nothing)? There might be other scenarios to consider.

**Comment by jbigot** [comment]
Regarding your first comment, this was exactly my point, the before/after notions might sometimes not be completely clear when ordering events happening on different parallel FS.

Regarding your 2nd point, I agree that it should be up to the user. What about loading data as for a fresh start but returning an error code from FTI_Init to let him choose?

**Comment by leobago** [comment]
Yes, that seems to be a good compromise. I will try to think on other weird scenarios but this suggestion looks good.

**Comment by sclaomir** [comment]
I also agree that the check should be made during FTI_Init just like it works now. And if library can't find valid checkpoint, it will be fresh start. We can inform user, but we are not able to predict all user mistakes.

**Comment by leobago** [comment]
Sounds good. Then instead of calling `FTI_Abort` we can get a new ExecID, set `FTI_Exec.Reco` to 0 and then return `FTI_NSCS`.

**Comment by jbigot** [comment]
> and then return FTI_NSCS.
What about introducing a new value the user can specifically check for

**Comment by leobago** [comment]
Yes, something like `#define FTI_BADI -2` to inform about a bad initialization due to failed recovery could be good. In addition, we should print a Warning message explaining what happened.

**Comment by sclaomir** [comment]
Indeed, it is quite common approach to define in libraries possible error values and corresponding error strings. Leo, would you be able to provide a list of all possible errors you are aware of?

**Comment by leobago** [comment]
I will think about it. For the time being I think we can simply do a `FTI_Print("Recovery failed, assuming fresh restart...", FTI_WARN)`.

**Comment by leobago** [comment]
@kellekai could you please take care of fixing this bug? Thanks!

**Comment by leobago** [comment]
Solved.
